### ISSUE TITLE
Overlapping title texts

### ISSUE THREAD

**Issue by comomac** [ninja-software/coffee-bot#1]
The title "Coffee Tracker" overlaps with "Coffee Today" and "All time" on small screen.

Suggest either hide "Coffee Tracker on small text or put above rest of other texts.

![Screenshot from 2020-02-03 17-03-36](https://user-images.githubusercontent.com/3762767/73639511-800c6480-46a7-11ea-8f1b-a025d5ededfa.png)

**Comment by ghost** [comment]
Closed with commit d2cf010b1dc25c97634e3f5bac73727152053fbe
